load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "highway_fingerprint",
    hdrs = ["highway_fingerprint.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/hash",
        "@com_google_absl//absl/strings:string_view",
    ],
)
