load("@rules_cc//cc:cc_library.bzl", "cc_library")

licenses(["notice"])

cc_library(
    name = "timestamp_cc_proto",
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:protobuf"],
)

