sharing/linux/quickshare-gnome-extension/extension.js usr/share/gnome-shell/extensions/quickshare@scottydev40.github.io
sharing/linux/quickshare-gnome-extension/metadata.json usr/share/gnome-shell/extensions/quickshare@scottydev40.github.io
sharing/linux/quickshare-gnome-extension/stylesheet.css usr/share/gnome-shell/extensions/quickshare@scottydev40.github.io
sharing/linux/quickshare-gnome-extension/dev.scotty.Scotty-symbolic.svg usr/share/gnome-shell/extensions/quickshare@scottydev40.github.io
