debian/tmp/usr/bin/scotty usr/bin
debian/tmp/usr/lib/scotty usr/lib
debian/tmp/usr/lib/systemd/user/scotty.service usr/lib/systemd/user
debian/tmp/usr/share/applications/dev.scotty.Scotty.desktop usr/share/applications
debian/tmp/usr/share/dbus-1/services/dev.scotty.Scotty.service usr/share/dbus-1/services
debian/tmp/usr/share/icons/hicolor usr/share/icons
debian/tmp/usr/share/metainfo/dev.scotty.Scotty.metainfo.xml usr/share/metainfo
debian/scotty.1 usr/share/man/man1
