load("@rules_cc//cc:cc_library.bzl", "cc_library")

licenses(["notice"])

cc_library(
    name = "connections_log_cc_proto",
    hdrs = ["connections_log.pb.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "sharing_log_cc_proto",
    hdrs = ["sharing_log.pb.h"],
    visibility = ["//visibility:public"],
)

